version: '3.2'
services:
  cypress:
    image: "cypress/included:13.8.1"
    environment:
      - CYPRESS_baseUrl=https://webdriveruniversity.com
    working_dir: /e2e
    volumes:
      - ./:/e2e
      - ./cypress:/e2e/cypress